---
- name: provisioning a New EC2 Instance using ansible playbook
  hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:
    - name: launch an ec2 instance in aws
      amazon.aws.ec2_instance:
        name: "General-instance"
        vpc_subnet_id: "subnet-0421d5a3e49a512f7"
        region: "ap-south-1"
        key_name: "myvm"
        instance_type: t2.micro
        security_group: default
        network:
          assign_public_ip: true
        image_id: ami-06984ea821ac0a879
        tags:
          Environment: Testing
        aws_access_key: XXXXXXXX
        aws_secret_key: XXXXXXXX
  

    
