---
- name: provisioning a New EC2 Instance using ansible playbook
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
    keypair: myvm
    instance_type: t2.micro
    image: ami-0ee23bfc74a881de5
    wait: yes
    group: webserver
    count: 1
    region: ap-south-1
    security_group: ec2-security-group

  tasks:
    - name: Create a security_group
      local_action:
        module: ec2_group
        name: "{{ security_group }}"
        description: security_group for webserver
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: basic_firewall

    - name: Launch the new EC2 Instance
      local_action: ec2
                  group={{ security_group }} 
                  instance_type={{ instance_type}} 
                  image={{ image }} 
                  wait=true 
                  region={{ region }} 
                  keypair={{ keypair }}
                  count={{count}}
      register: ec2
    - name: Task 
      local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          name: MyTargetEc2Instance
    
